# Generated by Django 3.2.20 on 2023-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Image', models.CharField(max_length=10000)),
                ('Description', models.CharField(max_length=500)),
                ('Price', models.FloatField(max_length=500)),
                ('Color', models.CharField(max_length=10)),
            ],
        ),
    ]
